- name: Развертывание локального веб-окружения с базовой защитой
  hosts: localhost # 127.0.0.1
  connection: local # не использовать ssh
  become: true # использовать sudo
  gather_facts: true
  roles:
    - web_env
