- name: Обновить кэш APT
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Не обновлять, если кэш свежее 1 часа
  become: true

- name: Установить Docker и Docker Compose
  apt:
    name:
      - docker
      - docker-compose
    state: present
  become: true

- name: Запустить и включить Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true
